added task to build/push images to remote registry

diff --git a/Taskfile.yaml b/Taskfile.yaml
--- a/Taskfile.yaml
+++ b/Taskfile.yaml
@@ -37,6 +37,29 @@ tasks:
          .
     dir: ./
 
+  push-image:
+    desc: Push Docker image for the given app
+    deps:
+      - build-image
+    vars:
+      app: '{{.app | default "server"}}'
+      tag: '{{.tag | default "latest"}}'
+    requires:
+      vars:
+        - DOCKER_REGISTRY_URL
+    preconditions:
+      - sh: '[ "{{.app}}" = "server" ] || [ "{{.app}}" = "worker" ] || [ "{{.app}}" = "scheduler" ]'
+        msg: "❌ Error: invalid app '{{.app}}', valid options are server, worker, or scheduler."
+    cmds:
+      - |
+        if [ -n "${DOCKER_REGISTRY_URL:-}" ]; then
+          echo "❌ Error: missing DOCKER_REGISTRY_URL environment variable." >&2
+          exit 1
+        fi
+        docker tag {{.name}}-{{.app}} {{.DOCKER_REGISTRY_URL}}/{{.app}}:{{.tag}}
+        docker push {{.DOCKER_REGISTRY_URL}}/{{.app}}:{{.tag}}
+    dir: ./
+
   compose:
     desc: Docker compose
     vars:
